HtmlHelperi/HtmlHelperi/Models/Adresa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HtmlHelperi.Models
{
    public class Adresa
    {
        public string Ulica { get; set; }
        public string KucniBroj { get; set; }
        public int Kat { get; set; }
    }
}

HtmlHelperi/HtmlHelperi/Models/Osoba.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HtmlHelperi.Models
{
    public class Osoba
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string MjestoStanovanja { get; set; }
        public string Spol { get; set; }
        public bool Zaposlen { get; set; }
    }
}

HtmlHelperi/HtmlHelperi/Models/OsobaMeta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace HtmlHelperi.Models
{
    [DisplayName("Osoba")]
    public class OsobaMeta
    {
        [HiddenInput(DisplayValue =false)]
        public int OsobaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        
        [Display(Name ="Mjesto stanovanja")]
        [UIHint("TemplMjesta")]
        public string MjestoStanovanja { get; set; }

        [UIHint("TemplSpol")]
        public string Spol { get; set; }

        public bool Zaposlen { get; set; }

        [DataType(DataType.Date)]
        public DateTime DatumRodjenja { get; set; }

        [UIHint("MultilineText")]
        public string Napomena { get; set; }
        public Adresa AdresaOsobe { get; set; }
    
    }
}

HtmlHelperi/HtmlHelperi/Models/OsobaTempl.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HtmlHelperi.Models
{
    public class OsobaTempl
    {
        public int OsobaId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string MjestoStanovanja { get; set; }
        public string Spol { get; set; }
        public bool Zaposlen { get; set; }
        public DateTime DatumRodjenja {get; set;}
        public string Napomena { get; set; }
        public Adresa AdresaOsobe { get; set; }
    }
}

HtmlHelperi/HtmlHelperi/Controllers/HtmlHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HtmlHelperi.Models;

namespace HtmlHelperi.Controllers
{
    public class HtmlHelpersController : Controller
    {
        // GET: HtmlHelpers
        public ViewResult OsnovniHelperi()
        {
            return View();
        }

        private string[] mjesta = new string[] { "Split", "Osijek", "Rijeka", "Zagreb" };

        public ViewResult FormHelper()
        {
            ViewBag.Mjesta = mjesta;
            return View(new Osoba());
        }

        [HttpPost]
        public ViewResult FormHelper (Osoba osoba)
        {
            ViewBag.Mjesta = mjesta;
            ViewBag.Poruka = "Podaci uneseni!";
            return View(osoba);

        }

        public ViewResult StrongTypedHelper()
        {
            ViewBag.Mjesta = mjesta;
            return View(new Osoba());
        }

        [HttpPost]
        public ViewResult StrongTypedHelper(Osoba osoba)
        {
            ViewBag.Mjesta = mjesta;
            ViewBag.Poruka = "Podaci uneseni!";
            return View(osoba);
        }
    }
}

HtmlHelperi/HtmlHelperi/Controllers/MetaDatahtmlHelperiController.cs
using HtmlHelperi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HtmlHelperi.Controllers
{
    public class MetaDatahtmlHelperiController : Controller
    {
        // GET: MetaDatahtmlHelperi
        public ViewResult MetaDataView()
        {
            return View(new OsobaMeta());
        }

        [HttpPost]
        public ViewResult MetaDataView(OsobaMeta osoba)
        {
            return View("HtmlLabelDisplay", osoba);
        }

        public ViewResult MetaDataView2()
        {
            return View(new OsobaMeta());
        }

        [HttpPost]
        public ViewResult MetaDataView2(OsobaMeta osoba)
        {
            return View("HtmlLabelDisplay", osoba);
        }
    }
}

HtmlHelperi/HtmlHelperi/Controllers/TemplHtmlHelperiController.cs
using HtmlHelperi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HtmlHelperi.Controllers
{
    public class TemplHtmlHelperiController : Controller
    {
        // GET: TemplHtmlHelperi
        public ViewResult HtmlEditorView()
        {
            return View(new OsobaTempl());
        }

        [HttpPost]
        public ViewResult HtmlEditorView(OsobaTempl osoba)
        {
            return View("HtmlLabelDisplay", osoba);
        }

        public ViewResult EditorModelView()
        {
            return View(new OsobaTempl());
        }

        [HttpPost]
        public ViewResult EditorModelView(OsobaTempl osoba)
        {
            return View("HtmlLabelDisplay", osoba);
        }
    }
}

HtmlHelperi/HtmlHelperi/Views/HtmlHelpers/FormHelper.cshtml
@model HtmlHelperi.Models.Osoba
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FormHelper</title>
    <style>
        label{
            display:inline-block;
            width:150px;
            margin: 5px;
        }
        .redColor{
            color:red;
        }
    </style>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            <div>
                <label>Ime:</label>
                @Html.TextBox("Ime")
            </div>
            <div>
                <label>Prezime:</label>
                @Html.TextBox("Prezime")
            </div>
            <div>
                <label>Email:</label>
                @Html.TextBox("Email")
            </div>
            <div>
                <label>Mjesto stanovanja:</label>
                @Html.DropDownList("MjestoStanovanja", new SelectList((string[])ViewBag.Mjesta), "--Odaberi--")
            </div>
            <div>
                <label>Spol:</label>
                @Html.RadioButton("Spol", "M", true) Muško
                @Html.RadioButton("Spol", "Z", false) Žensko
            </div>
            <div>
                <label>Zaposlen</label>
                @Html.CheckBox("Zaposlen", false)
            </div>
            <input type="submit" value="Pošalji" />
        }
    </div>
    <p>
        <label class="redColor">@ViewBag.Poruka</label>
    </p>
</body>
</html>

HtmlHelperi/HtmlHelperi/Views/HtmlHelpers/OsnovniHelperi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OsnovniHelperi</title>
    <style>
        div{
            padding-bottom:5px;
        }
    </style>
</head>
<body>
    <div> 
        @Html.CheckBox("chk1", true) CheckBox
    </div>
    <div>
        @Html.RadioButton("rbu","rbu1", true) RadioButton 1
        <br />
        @Html.RadioButton("rbu", "rbu2", false) RadioButton 2
    </div>
    <div>
        @Html.Hidden("hid1", "tekst")
    </div>
    <div>
        @Html.Password("pas1", "tekst")
    </div>
    <div>
        @Html.TextBox("txt1", "tekst")
    </div>
    <div>
        @Html.TextArea("tar1", "tekst", 10, 15, null)
    </div>
    <div>
        @Html.DropDownList("ddl1", new SelectList(new[] { "Muško", "Žensko"}), "--Odaberi spol--")
    </div>
    <div>
        @Html.ListBox("lb1", new MultiSelectList(new [] { "Jabuka", "Kruška", "Banana"}))
    </div>
</body>
</html>

HtmlHelperi/HtmlHelperi/Views/HtmlHelpers/StrongTypedHelper.cshtml
@model HtmlHelperi.Models.Osoba
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StrongTypedHelper</title>
    <style>
        label{
            display:inline-block;
            width:150px;
            margin:5px;
        }
        .redColor{
            color:red;
        }
    </style>
</head>
<body>
    <div> 
        @using (Html.BeginForm("StrongTypedHelper", "HtmlHelpers"))
        {
            <div>
                <label>Ime:</label>
                @Html.TextBoxFor(x=>x.Ime)
            </div>
            <div>
                <label>Prezime:</label>
                @Html.TextBoxFor(x=>x.Prezime)
            </div>
            <div>
                <label>Email:</label>
                @Html.TextBoxFor(x=>x.Email)
            </div>
            <div>
                <label>Mjesto stanovanja:</label>
                @Html.DropDownListFor(x=>x.MjestoStanovanja, new SelectList((string[])ViewBag.Mjesta), "--Odaberi--")
            </div>
            <div>
                <label>Spol:</label>
                @Html.RadioButtonFor(x=>x.Spol, "M", true) Muško
                @Html.RadioButtonFor(x=>x.Spol, "Z", false) Žensko
            </div>
            <div>
                <label>Zaposlen:</label>
                @Html.CheckBoxFor(x=>x.Zaposlen, false)
            </div>
            <input type="submit" value="Pošalji" />
        }
    </div>
    <p>
        <label class="redColor">@ViewBag.Poruka</label>
    </p>
</body>
</html>

HtmlHelperi/HtmlHelperi/Views/MetaDatahtmlHelperi/EditorTemplates/TemplMjesta.cshtml
@Html.DropDownListFor(x=>x, new SelectList(new string[] { "Split", "Osijek", "Rijeka", "Zagreb"}), "--Odaberi--")
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TemplMjesta</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

HtmlHelperi/HtmlHelperi/Views/MetaDatahtmlHelperi/EditorTemplates/TemplSpol.cshtml
@Html.RadioButtonFor(x=>x, "M", true) Muško
@Html.RadioButtonFor(x=>x, "Z", false) Žensko
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TemplSpol</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>