projekt 6_3_vj/projekt 6_3_vj/Models/Artikl.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace projekt_6_3_vj.Models
{
    
    public class Artikl
    {
        [UIHint("TemplateKategorija")]
        public string Kategorija { get; set; }
        public string Naziv { get; set; }
        public decimal Cijena { get; set; }

        [Display(Name ="Količina")]
        public int Kolicina { get; set; }
    }
}

projekt 6_3_vj/projekt 6_3_vj/Controllers/ListaArtikalaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using projekt_6_3_vj.Models;

namespace projekt_6_3_vj.Controllers
{
    public class ListaArtikalaController : Controller
    {
        //string[] kategorija = new string[] { "Hrana", "Kućanstvo", "Vrt", "Rekreacija" };
        // GET: ListaArtikala
        public ActionResult UnesiArtikl()
        {

            ViewBag.Kategorije = new string[] { "Hrana", "Kućanstvo", "Vrt", "Rekreacija" };
            return View(new Artikl());
        }

        [HttpPost]
        public ViewResult DodajArtikl(Artikl artikl)
        {
            if (Session["Artikli"] != null)
            {
                List<Artikl> artikli = (List<Artikl>)Session["Artikli"];
                artikli.Add(artikl);
                Session["Artikli"] = artikli;
            }
            else
            {
                List<Artikl> artikli = new List<Artikl>();
                artikli.Add(artikl);
                Session["Artikli"] = artikli;
            }
            return View(Session["Artikli"]);
        }
    }
}

projekt 6_3_vj/projekt 6_3_vj/Views/ListaArtikala/DodajArtikl.cshtml
@using projekt_6_3_vj.Models
@model List<Artikl>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DodajArtikl</title>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            padding: 10px;
        }
    </style>
</head>
<body>
    <h3>Lista artikala</h3>
    <table>
        <tr>
            <th>Naziv</th>
            <th>Kategorija</th>
            <th>Cijena</th>
            <th>Količina</th>
        </tr>
        @foreach (Artikl artikl in (List<Artikl>)Model)
        {
            <tr>
                <td>@artikl.Naziv</td>
                <td>@artikl.Kategorija</td>
                <td>@artikl.Cijena</td>
                <td>@artikl.Kolicina</td>
            </tr>
        }
    </table>
    <a href="/ListaArtikala/UnesiArtikl">Unesi artikl</a>
</body>
</html>

projekt 6_3_vj/projekt 6_3_vj/Views/ListaArtikala/TemplateKategorija.cshtml
@Html.DropDownListFor(x => x, new SelectList((string[])ViewBag.Kategorije), "--Kategorija--")

projekt 6_3_vj/projekt 6_3_vj/Views/ListaArtikala/UnesiArtikl.cshtml
@model projekt_6_3_vj.Models.Artikl
@{
    Layout = null;
    Html.EnableClientValidation(false);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UnesiArtikl</title>
    <style>
        label {
            width: 150px;
            padding-top: 10px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <h3>@Html.LabelForModel()</h3>
    <div>
        @using (Html.BeginForm("DodajArtikl", "ListaArtikala"))
        {
           
               @Html.EditorForModel()

            <input type="submit" value="Dodaj" />
        }
    </div>
</body>
</html>